POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiYzIiLCJpZCI6IjY1MzUwZWFmMDY0YmJiY2U3NmFlZTc0MCIsImlhdCI6MTY5Nzk3NjExMH0.BgfxChBVFFmwCGUYLIuV_5FUZ8tx2RDvdyvdklL0ieY
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2NTMzOGIwOTk1MTM5MTkxOWIwZjE0NDAiLCJpYXQiOjE2OTc5NzU0NDh9.9SFnUV_5jnMV9uq3fn_cfERUr9TE-GFy1YgbyBeXFgk

{  "title": "loggedInUserCreate8",
  "author": "Sid",
  "url": "abc.com",
  "likes": 5
}